== Summary

link:https://github.com/opengeospatial/WFS_FES[OGC Web Feature Service (WFS) 3.0] is a revision of the
link:http://www.opengeospatial.org/standards/wfs[WFS standard] that proposes a
modernized service architecture, that follows the current Web architecture, has
a focus on the developer experience, supports the link:https://www.openapis.org/[OpenAPI specification], and
modularizes WFS into building blocks for fine-grained access to spatial data
that can be used in Application Programming Interfaces (APIs) for data.

This document reviews the work on this next generation of OGC web services
("NextGen services" or "Next Generation APIs") from the perspective of supporting complex
three-dimensional (3D) data or complex data schemas. The goal is to identify the best service solution
for these particular needs, whether the results are WFS 3.0 extensions or other
approaches. In this context the approach of the NextGen services is not of
monolithic web services, but API building blocks. This is an important point.
The same API should be able to support requirements that currently require
separate OGC web services, e.g. a WFS and a 3D Portrayal Service (3DPS).

The report includes proposals on how to extend the NextGen service architecture
with API building blocks for complex data, complex queries and 3D portrayal.
WFS 3.0, Part 1, is used as the starting point for the NextGen service architecture.
The proposals are based on existing requirements and use cases as well as
existing support for developers to simplify implementation.

The work has found no general issues with migrating current WFS, 3DPS, Web Map
Tile Service (WMTS) and Web Map Service (WMS) capabilities to the OGC NextGen
architecture. On the contrary, the
NextGen approach improves the consistency of the interface and removes
redundancies (e.g., between the feature access in WFS and the feature info
requests in the other standards).

=== Requirements & Research Motivation

The current work on WFS 3.0 has focused on simple features and interaction,
interrogation and extraction of these. However, there are more complex use
cases that require 3D data and/or more complex data schemas to achieve a
user-desired outcome.

This report documents real-world use cases and requirements that feature
servers will have to support in the future, besides the essential capabilities
specified in Part 1 of the WFS 3.0 series. These will include the following:

* Querying / filtering features based on properties of related or nested objects
or structured data types, including cases where more than one level of
relationships/nesting is used;
* Querying / filtering features based on expressions built from complex predicates
consisting of predicate groups and combinations of logical operators;
* Querying feature data and returning only parts of the features (selected
properties, a single property only, etc.);
* Access to and query of solid geometries and other geometries in a 3D Coordinate
Reference System (CRS);
* Use of responses for display in a web browser;
* Accessing different versions (including historic representations) of features.

The use cases cover aspects like CityGML, CityGML ADEs, 3DPS, and WFS 2.0
interactions, but use other complex data schemas as background, too.

Based on the identified requirements, this report addresses the following
aspects:

* Assessment of what use cases, especially those that utilize 3D or more
complex data schemas, would require more complex interactions than the
current WFS 3.0, Part 1, draft would provide;
* Assessment of current OGC standards and community specifications on the basis
of both supporting the uses cases captured and alignment to NextGen service
approaches, including a review around the interaction between 3DPS and WFS 2.0;
* Recommendations for the most appropriate way to support these use cases
within the NextGen service architecture.

Developer requirements have to be taken into account in the design. That is, the
implementation of the proposed design should be as simple as possible (given the
advanced, complex requirements). This includes research for available libraries
that support implementations. The OGC community is not the only one implementing
rich queries on complex data.

=== Prior-After Comparison

The current work on WFS 3.0 in the WFS/FES Standards Working Group (SWG) has
focused on simple features and interaction, interrogation and extraction
of these. However, there are more
complex use cases that require 3D data and/or more complex data schemas to
achieve the results that a user is looking for.

This work propose extensions to the NextGen service architecture to support
such use cases.

Initial discussions about related topics are:

* Placeholder issue in the WFS 3.0 repository for richer query capabilities:
link:https://github.com/opengeospatial/WFS_FES/issues/79[WFS 3.0 Search extension]
* Representational State Transfer (REST) binding in the WFS 2.x and Filter
Encoding Standard (FES) 2.x draft specifications: link:https://portal.opengeospatial.org/index.php?m=projects&a=view&project_id=390&tab=2&artifact_id=56200[Document folder in the OGC portal (only accessible to OGC WFS/FES SWG members)]

Like the work in the WFS/FES SWG on WFS 3.0, the work on this report has been open
to the public from the beginning in order to allow early feedback from developers
already during the testbed.

The formal review of the draft report before it will be submitted to the OGC
Technical Committee for consideration and publication as an OGC Engineering Report
will be by the WFS/FES SWG.

=== Recommendations for Future Work

See <<recommendations,the chapter "Recommendations">>. The OGC Innovation Program
would be ideal to continue work on the recommendations 1 to 4 based on
<<rec-6,recommendation 6 (validate and refine recommendations through implementation)>>:

* <<rec-1,Recommendation 1a: Specify WFS 3.0 extensions for improved fetching of feature data>>
* <<rec-1,Recommendation 1b: Make CQL an OGC standard on its own>>
* <<rec-2,Recommendation 2: Migrate additional OGC web service standards to the NextGen architecture>>
* <<rec-3,Recommendation 3: Investigate if/how GraphQL could be used to query a dataset>>
* <<rec-4,Recommendation 4: Consider the use of CityJSON for 3D city models>>

<<rec-5,Recommendation 5 (develop guidance for implementing additional search capabilities)>>
could also be a candidate for the development of a Guide as part of a Testbed.

<<rec-7,Recommendation 7 (register media types for encodings to be used in NextGen services)>>
is future work for the bodies that govern the i3s, 3D Tiles and CityJSON specifications.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the
contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Clemens Portele _(editor)_ |interactive instruments GmbH
|Volker Coors |Hochschule für Technik Stuttgart
|====================

// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
