[[use_cases]]
== Use cases

=== Introduction

This section will document real-world use cases and requirements that more advanced feature
servers should support in the future, besides the essential capabilities
specified in Part 1 of the WFS 3.0 series.

All query examples are used in practice, either as queries submitted by a client, in
stored queries of a WFS or in Styled Layer Descriptor (SLD)/Symbology Encoding (SE)
documents defining layers based on feature data.

The use cases cover aspects like CityGML, CityGML Application Domain Extensions (ADEs),
3DPS, and WFS 2.0 interactions, but use other complex data schemas, too.

We identify for each use case example why the example has been
included in this report. There is at least one example for each of the following
aspects:

* Querying features based on properties of related or nested objects or structured data types (one level)
* Querying features based on properties of related or nested objects or structured data types (several levels)
* Querying features based on expressions built from complex predicates consisting of predicate groups and combinations of logical operators
* Querying feature data and returning only parts of the features (selected properties, a single property only, etc.)
* Querying feature data and returning additional features linked to the selected features
* Access to and query of solid geometries and other geometries in a 3D CRS
* Use of responses for display in a web browser
* Accessing different versions (including historic representations) of features

include::5-use-cases-cadastre.adoc[]

include::5-use-cases-heatingdemand.adoc[]
