[[recommendations]]
== Recommendations

This chapter builds on the analysis in the previous chapters and derives
recommendations for the most appropriate way to support the
use cases within the NextGen service architecture.

NOTE: This is a draft version of the document and it is expected that the
recommendations will change based on feedback and discussions until the OGC
TC meeting in December 2018.

[[rec-1a]]
=== Recommendation 1a: Specify WFS 3.0 extensions for improved fetching of feature data

This could be multiple documents or a single document with multiple conformance classes.

1. One conformance class should support CQL queries on dataset and collection
resources as outlined <<cql,here>>. The CQL should be restricted to the profile
that is implemented in GeoTools and other libraries (e.g. no support for
compound attributes, relationships, attributes with multiple values).
Alternatively, another simple, easy to implement syntax that is straightforward
to map to queries on relational databases and document stores could be
implemented. The STAC JSON syntax could be an option.

2. If CQL is supported, another conformance class should add support for the
richer queries including the capabilities for the "complex feature handling"
use cases discussed in this document (see <<cql-examples,these examples>>).

3. Add a path `/items` in another conformance class to support fetching
features from all the sub-collections in a dataset. A query parameter
`collections` should be added to select features from a subset of the
collections.

4. In another conformance class, add a `resolve` query parameter to the
feature collection and feature resources as outlined <<resolve,here>>. If
the CQL queries support nested structures and relationships (see item 2 above),
the `resolve` parameter should supported the extended property notation, too.

5. In another conformance class, add a `properties` query parameter to the
feature collection and feature resources as outlined <<properties,here>>. Note
that additional conformance classes will need to be specified for encodings
how to map property names to the content. This should be done for the GeoJSON
and GML encodings specified in the WFS 3.0 Core. Again, if the CQL queries
support nested structures and relationships (see item 2 above), the `properties`
parameter should support the extended property notation, too.

In addition, the Core should be amended to support
<<_querying_different_versions,the capability to select, by default, only features that are valid "now">>.
This is useful for datasets where the features are versions of a real-world entity, valid for a given time period.
"By default" means, without an explicit `time` parameter. The default behaviour
could be stated in the feature collection metadata, the default would be the
current WFS 3.0 behaviour (all features that meet the explicit selection
criteria).

[[rec-1b]]
=== Recommendation 1b: Make CQL an OGC standard on its own

If CQL would be supported by a WFS extension as a result of the
recommendation 1 above, it should be extracted from
the Catalogue Service standard and become a standard on its own.

The CQL standard should provide a clear and unambiguous specification of the
query language and requirements for implementations. It also clarify how
CQL provides API building blocks that can be reused by WFS 3.0 or other
NextGen standards.

[[rec-2]]
=== Recommendation 2: Migrate additional OGC web service standards to the NextGen architecture

The analysis has outlined how current 3DPS, WMTS and WMS that operate on feature data
could be implemented in the NextGen architecture. Other activities in OGC Testbed 14
(see, for example deliverable D021 "Secure Resource Oriented Geospatial Data
Handling Engineering Report") as well as the OGC Vector Tiles Pilot have made
experiments along the same lines.

These activities should continue to validate the NextGen goal to support
access to spatial data using consistent API building blocks.
This is inline with the ongoing NextGen discussions in the
OGC Architecture Domain Working Group (DWG) and the OGC OWS Common SWG.

[[rec-3]]
=== Recommendation 3: Investigate if/how GraphQL could be used to query a dataset

GraphQL is a highly popular query mechanism to fetch data with support for complex
data structures. It is relatively straightforward to use and at the same time allows
highly customizable queries that return exactly the data that the client wants.

Its architecture is orthogonal to the NextGen architecture which is based on
the architecture of the web. That is, support for GraphQL would be complementary
to the WFS 3.0 / NextGen approach.

It is recommended to explore how GraphQL endpoints could support complex feature
handling use cases in more detail than it was possible in Testbed 14. This should
include prototypes.

Experiments should focus on JSON encodings.

Open questions include:

* To what extent should existing encodings like GeoJSON and CityJSON be used in
GraphQL schemas?
* Would there be any value in having a general mapping from an application schema
to a GraphQL query schema?
* How can GraphQL queries be extended to support spatial searches - without
the need to discard the tooling?

In Testbed-14 an <<graphql-example,initial, simple experiment>> has been
included that looked into the first of the two questions. The results
seem to indicate that GraphQL schemas for querying feature data probably
should not use GeoJSON/CityJSON, but tailored schemas for the specific
query needs. If this conclusion is confirmed by additional, more substantial
experiments, then supporting a GraphQL query endpoint for feature data
should not be subject to standarization as a WFS extension.
Instead guides or tutorials would be more appropriate and useful.

Or, alternatively, there could be value in specifying a general (default)
mapping from an application schema to a GraphQL query schema. This could
be used as a starting point, too, and be tailored towards the specific
application needs of the deployment.

In addition, the third question could be a potential subject of future
standarization. That is, how to consistently support spatial searches in
GraphQL queries.

[[rec-4]]
=== Recommendation 4: Consider the use of CityJSON for 3D city models

Due to the current popularity of JSON (over XML), WFS 3.0 implementations
should not only support an XML/GML-based encoding, but also a JSON-based encoding.
As GeoJSON does not meet the needs of 3D city models, CityJSON is a primary
starting point. CityJSON is not yet a standard, but
link:https://github.com/w3c/strategy/issues/114[investigations are ongoing].

[[rec-5]]
=== Recommendation 5: Develop guidance for implementing additional search capabilities

Provide guidance on how implementations could support additional, more advanced
query mechanisms that best fit their encoding(s) and datastore. These probably
should not be promoted as OGC standards as the details may be implementation
dependent and too few implementations would support the same advanced
capabilities.

Examples could be:

* the use of XQuery on a document store that supports XML or a XML database;
* the use of WFS 2.0 Query / FES 2.0 Filter in an implementation that supports
WFS 2.0 in addition to WFS 3.0;
* the use of (Geo)SPARQL in an implementation that uses a triple store;
* the use of a bespoke query language with a straightforward mapping to the
underlying datastore (for example, a WFS 3.0 that uses a MongoDB datastore
probably would support a query mechanism that directly maps to the
link:https://docs.mongodb.com/manual/tutorial/query-documents/[native MongoDB queries]).

The <<_general_considerations,general considerations on the API design>>
discussed in chapter 7 should be taken into account when developing the guidance.

In particular for query languages that are close to the query mechanisms of the
backend datastore, the security implications should be considered and servers
should inspect a query thoroughly before executing it on the backend datastore
(for example, the queries should be analysed for malicious content or to verify
that they do not place an undesired burden on the server. It should not be
forgotten that exposing rich query capabilities via a Web API is a potential
security risk.

[[rec-6]]
=== Recommendation 6: Validate and refine recommendations through implementation

In general, the recommendations above have not been tested yet in implementations.
Validation and refinement through implementation is, however, fundamental
to the WFS 3.0 and NextGen process. All recommendations should thus be
validated in multiple implementations before considering them for
standardisation.

[[rec-7]]
=== Recommendation 7: Register media types for encodings to be used in Web APIs

The selection of the data format used in a response must support HTTP content
negotiation. This requires that format can be identified using media types
that should be registered with IANA. For example, media types should be registered
for i3s, 3D Tiles, CityJSON and perhaps also for CityGML.
